### ISSUE TITLE
The data used in the demo script can't be download.

### ISSUE THREAD

**Issue by zimo-5kk** [yuanlong-o/Deep_widefield_cal_inferece#1]
I have carefully checked  my browser of the link in the follow figure:
![image](https://github.com/yuanlong-o/Deep_widefield_cal_inferece/assets/83194946/6c8d66d0-14b5-4fd2-b774-4882f3f23288)
But I still can't open the webpage, could you please check if the link is still correct?
Sincerely thanks!

**Comment by yuanlong-o** [comment]
Sorry for the inconvenience. We've confirmed the links are expired. We will
update those links shortly. At this moment, the link for the paired 2p-wd
dataset (
https://drive.google.com/drive/folders/1OBcQUY-vsIPljSBChFfn-zqAYtYvDZ4A)
still lives, so if you are eagering for a test it can be an option.

**Comment by yuanlong-o** [comment]
06182023 links are renewed. pls enjoy
