### ISSUE TITLE
Error in NAOMi_1p fun_time_trace_generation

### ISSUE THREAD

**Issue by mk-mccann** [yuanlong-o/Deep_widefield_cal_inferece#3]
Hello again, 

I'm experiencing an error with the bundled NAOMi_1p package, in `TimeTraceCode/fun_time_trace_generation`, line 389:

```
Incorrect number or types of inputs or outputs for function 'resample'.

Error in fun_time_trace_generation (line 389)
    S.soma = resample(double(S.soma.'), r2, r1).';
``` 

I looked on the repository for NAOMi_sim, and this function isn't present there, so I''m at a loss for what the issue is, if it's a syntax error or otherwise.

**Comment by yuanlong-o** [comment]
Hi McCann,

Sorry for the inconvenience. The resample function is a built-in function
in matlab, see https://www.mathworks.com/help/signal/ref/resample.html. Let
me know if you need more help.

yuanlong

**Comment by mk-mccann** [comment]
Yep, realized this was me missing a toolbox. Closing now. thanks.
